### ISSUE TITLE
usar Exceptions

### ISSUE THREAD

**Issue by garciagabriel** [AlmadaBraian/BibliotecaMaven#1]
Para los errores de cuando no se puedan prestar copias usar excepciones

**Comment by AlmadaBraian** [comment]
Se agregaron las excepciones solicitadas. Commits on Feb 12, 2021 
https://github.com/SpoilerFest/BibliotecaMaven/commit/c8d9bd2ab65c85286c55ff2dc9a10ee1d32965aa
