### ISSUE TITLE
Clase Biblioteca

### ISSUE THREAD

**Issue by garciagabriel** [AlmadaBraian/BibliotecaMaven#2]
public void reverse() -> Ya existe un metodo para hacer un reverse en la clase Collections

En los maps de tipo Map<Integer, Copia> , no hace falta iterar desde un keyset , haciendo un get de la clave ya podes sacar lo que necesitas

**Comment by AlmadaBraian** [comment]
Se quito el método reverse(). Se modificaron todas las iteraciones Map<Integer, Copia>.
Commits on Feb 12, 2021
https://github.com/SpoilerFest/BibliotecaMaven/commit/7932b1133f048e112e7254319a6e8965ffc60d1e
