### ISSUE TITLE
Devolucion trabajo integrador

### ISSUE THREAD

**Issue by garciagabriel** [AlmadaBraian/BibliotecaMaven#4]
Muy buen codigo, lo bueno es que hiciste lo de JPA y webservices para varias entidades.
El detalle a mejorar es los junit, ya que cuando lo que vos queres testear anda bien,entonces no hay que hacer un "fail'. 
Los fails solo los pones cuando algo esta mal, por ejemplo en testPrestarConExcesoPrestamos de LectorTest en vez de 

```
catch (LectorExcedeAlquileresException e) {
				fail("Lector exede alquileres permitidos");
			}
```

Deberia quedar vacio , 

```
catch (LectorExcedeAlquileresException e) {

			}
```

Porque el resultado esperado es que salte esa excepcion

**Comment by AlmadaBraian** [comment]
Se modificaron los JUnit segun lo indicado.
Feb 24, 2021
https://github.com/AlmadaBraian/BibliotecaMaven/commit/0e9b0c8d8a36d38668313f99608193010dce61de
